
/// Show a named definition.
///  - name (string): The string label of the definition (it is the key in the dictionary lookup).
/// - definition_env: The definition environment function used to draw the definition box, etc.
#let show_def(definition_env: x => x, name) = {
  /// The list of all definitions that can be looked up.
  ///
  /// = If you have a new definition, it should be added here.
  ///
  let all_definitions = (
    model: definition_env(
      title: "Mathematical Model",
      label: <def_model>,
      [
        A _mathematical model_ is a description of the world that is
        + created in the service of answering a question, and
        + where the complexity of the world has been abstracted away to numbers, quantities, and their relationships.
          #footnote[Other mathematical objects are also allowed.]
      ],
    ),
    diffeq: definition_env(
      title: "Differential Equation",
      label: <def_diffeq>,
      [
        A _differential equation_ is an equation relating a function to one or more of its
        derivatives.
      ],
    ),
    orderdiffeq: definition_env(
      title: "Order of a Differential Equation",
      label: <def_orderdiffeq>,
      [
        A differential equation is said to be _order $n$_ if the highest derivative that appears in the differential equation is the $n$th derivative.
      ],
    ),
    model_fit: definition_env(
      title: "Fitting a Model",
      label: <def_model_fit>,
      [
        Given a model $M$ with parameters $k_1$, $k_2$, #sym.dots and data $D$, fitting the model $M$ to the
        data $D$ is the process of finding values for the parameters $k_1$, $k_2$, #sym.dots so that $M$
        most accurately predicts the data $D$.
      ],
    ),
    slope_field: definition_env(
      title: "Slope Field",
      label: <def_slope_field>,
      [
        A _slope field_ for the differential equation $y' = f(x,y)$ is a collection of line segments that are tangent to different solutions of the differential equation.

        The line segments are generated by
        evaluating $f(x,y)$ over a rectangular grid of points, and at each point $(x,y)$ of the grid creating a line segment of slope $f(x,y)$.
        The length of the line segments is not important, but should be consistent.
      ],
    ),
    component_and_phase: definition_env(
      title: "Component Graph & Phase Plane",
      label: <def_component_and_phase>,
      [
        For a differential equation involving the functions $F_1$, $F_2$, #sym.dots, $F_n$, and
        the variable $t$, the _component graphs_ are the $n$ graphs
        of $(t, F_1 (t))$, $(t, F_2 (t))$, #sym.dots.

        The _phase plane_ or _phase space_ associated with the
        differential equation is the $n$-dimensional space with
        axes corresponding to the values of $F_1$, $F_2$, #sym.dots, $F_n$.
      ],
    ),
    equilibrium_solution: definition_env(
      title: "Equilibrium Solution",
      label: <def_equilibrium_solution>,
      [
        An _equilibrium solution_ to a
        differential equation or system of differential equations
        is a solution that is constant in the independent variable(s).
      ],
    ),
    equilibrium_classification_informal: definition_env(
      title: "Classification of Equilibria",
      label: <def_equilibrium_classification_informal>,
      [
        An equilibrium solution $f$ is called
        - _attracting_ if locally, solutions converge to $f$;
        - _repelling_ if there is a fixed distance so that locally, solutions tend away from $f$ by that fixed distance;
        - _stable_ if for any fixed distance, locally, solutions stay within that fixed distance of $f$; and,
        - _unstable_ if $f$ is not stable.
      ],
    ),
    equilibrium_classification_formal: definition_env(
      title: "Classification of Equilibria (Formal)",
      label: <def_equilibrium_classification_formal>,
      [
        An equilibrium solution $f$ is called
        - _attracting at time $t_0$_ if
          there exists $epsilon > 0$ such that for all solutions $g$ satisfying $abs(g(t_0) - f(t_0)) < epsilon$, we have $lim_(t -> infinity) f(t) = lim_(t -> infinity) g(t)$.
        - _repelling at time $t_0$_ if there exists $epsilon > 0$ and $delta > 0$ such that for all
          solutions $g$ that satisfy $0 < abs(g(t_0) - f(t_0)) < epsilon$ there exists $T in RR$ so that for all $t > T$ we have
          $abs(g(t) - f(t)) > delta$.
        - _stable at time $t_0$_ if for all $epsilon > 0$ there exists a $delta > 0$ such that for all solutions $g$ satisfying $abs(g(t_0) - f(t_0)) < delta$
          we have $abs(g(t) - f(t)) < epsilon$ for all $t > t_0$.
        - _unstable at time $t_0$_ if $f$ is not stable at time $t_0$.

        $f$ is called attracting/repelling/stable/unstable if it has the corresponding property for all $t$.
      ],
    ),
    phase_portrait: definition_env(
      title: "Phase Portrait",
      label: <def_phase_portrait>,
      [
        A _phase portrait_ or _phase diagram_ is the plot of a vector field in phase space where each vector rooted at $(x, y)$ is tangent to a solution curve passing through $(x, y)$ and its length is given by the speed of a solution passing through $(x, y)$.
      ],
    ),
    linear_dependence_algebraic: definition_env(
      title: "Linear Dependence & Independence (Algebraic)",
      label: <def_linear_dependence_algebraic>,
      [
        The vectors $arrow(v)_1, arrow(v)_2, dots, arrow(v)_n$ are _linearly dependent_ if there is a non-trivial linear combination of $arrow(v)_1, dots, arrow(v)_n$ that equals the zero vector.
        Otherwise they are _linearly independent_.
      ],
    ),
    linear_dependence_solutions: definition_env(
      title: "Linear Dependence & Independence of Solutions",
      label: <def_linear_dependence_solutions>,
      [
        The functions $arrow(v)_1(t), arrow(v)_2(t), dots, arrow(v)_(n)(t)$ are _linearly dependent_ if there is a non-trivial linear combination of $arrow(v)_1(t), dots, arrow(v)_(n)(t)$ that equals the zero vector for all $t in RR$, i.e. if there are constants $c_1, dots, c_n$ not all zero such that
        $c_1 arrow(v)_1(t) + c_2 arrow(v)_2(t) + dots + c_n arrow(v)_(n)(t) = 0$ for all $t in RR$.

        Otherwise they are _linearly independent_.
      ],
    ),
    eigensolution: definition_env(
      title: "Eigen Solution",
      label: <def_eigensolution>,
      [
        Given a system of differential equations
        $(dif arrow(r)) / (dif t) = M arrow(r),$
        where $M$ is a matrix with real entries, and an eigenvalue-eigenvector pair $(lambda, arrow(v))$ of the matrix $M$, we define the function
        $arrow(r)(t) = arrow(v) e^(lambda t)$
        to be an _eigen solution_ of the system.
      ],
    ),
    eulers_method: definition_env(
      title: "Euler's Method",
      label: <eulers_method>,
      [
        Let $y'(t)=f(t, y)$ be a differential and let $y$ be a solution satisfying $y(t_0)=y_1$.
        The _Euler approximation to $y$ with step size $Delta$_ is the sequence of points
        $(t_0,y_0)$, $(t_1, y_2)$, #dots, where
        $
          y_1 &= y_0 + Delta dot f(t_0, y_0) &quad t_1 &= t_0+Delta\
          y_2 &= y_1 + Delta dot f(t_1, y_1) &quad t_2 &= t_1+Delta\
          &#h(.3em) dots.v & &#h(.3em)dots.v \
          y_n &= y_(n-1) + Delta dot f(t_(n-1), y_(n-1)) &quad t_n &= t_(n-1)+Delta\
        $
      ],
    ),
    solution: definition_env(
      title: "Solution",
      label: <def_solution>,
      [
        A _solution_ to a differential equation on a domain $D$ is a function with domain $D$
        which satisfies the differential equation on $D$. (The domain $D$ is usually take to
        be a connected set like an interval.)
      ],
    ),
    matrix_form: definition_env(
      title: "Matrix Form",
      label: <def_matrix_form>,
      [
        A system of differential equations $ x'_1(t)=dots.c\
        x'_2(t)=dots.c\
        dots.v\ $ is written in _matrix form_ if it is expressed as
        $
          arrow(x)'(t) = M arrow(x)(t)
        $
        where $arrow(x)=mat(x_1; x_2; dots.v)$ and $M$ is a matrix with real entries.
      ],
    ),
    eulers_formula: definition_env(
      title: "Euler's Formula",
      label: <def_eulers_formula>,
      [
        Euler's formula states that for any real number $t$,
        $
          e^(i t) = cos(t) + i sin(t).
        $
      ],
    ),
  )

  /// Show the definition with the given name. `name` is a string.
  let _def_lookup(name) = {
    let ret = all_definitions.at(name, default: none)
    if ret == none {
      text(fill: red, [Definition not found. Available definitions are: #all_definitions.keys()])
    } else {
      ret
    }
  }

  _def_lookup(name)
}

