name: Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["*"]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Debug paths
              run: |
                  echo "Current directory: $(pwd)"
                  echo "Files in current directory:"
                  ls -la
                  ls book/typst/
            - name: Compile Typst Files
              uses: siefkenj/compile-typst-action@main
              with:
                  source_paths: "book/typst/book.typ book/typst/slides.typ book/typst/slides-white.typ"
                  output_paths: "book/typst/book.pdf book/typst/slides.pdf book/typst/slides-white.pdf"
                  fonts_path: "book/typst"

            # upload all the built PDFs as an artifact.
            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  include-hidden-files: true
                  # Include something from the root so the file tree matches the full file tree of the repo
                  # (otherwise everything is normalized to the closest common ancestor folder)
                  path: |
                      ./README.md
                      ./**/*.pdf

    build_website:
        name: Build Website
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout sources
              uses: actions/checkout@v4

            - name: Download textbook PDFs
              uses: actions/download-artifact@v4
              with:
                  name: build-artifacts
                  path: ./

            - name: Merge PDFs into website
              run: |
                  mkdir -p website/landing-page/assets/textbook
                  cp book/typst/*.pdf website/landing-page/assets/textbook/

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: website
                  path: website/landing-page

    deploy_to_github_pages:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' &&  (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        needs: build_website

        permissions:
            contents: read
            pages: write
            id-token: write

        concurrency:
            group: "pages"
            cancel-in-progress: false

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: Download website artifact
              uses: actions/download-artifact@v4
              with:
                  name: website
                  path: website

            - name: Setup Pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./website"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
